[package]
name = "quarto"
version = "0.1.0"
authors = ["Jonathan Mast <jon@jonmast.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
rayon = "1.3.0"
